/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import com.crio.starter.repository.JobRepository;

import lombok.extern.log4j.Log4j2;

import org.modelmapper.ModelMapper;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Scope;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;

@SpringBootApplication
@Log4j2
@EnableMongoRepositories(basePackageClasses = JobRepository.class)
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    
    // TIP:MODULE_RESTAPI: If your server starts successfully,
    // you can find the following message in the logs.
    // log.info("Congrats! Your BuilOutsQa server has started");

  }

  /**
   * Fetches a ModelMapper instance.
   *
   * @return ModelMapper
   */
  @Bean // Want a new obj every time
  @Scope("prototype")
  public ModelMapper modelMapper() {
    return new ModelMapper();
  }

}
